name: ghaith_project
version: 1.0.0+2
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.1.4
  retrofit: ^2.0.0
  json_annotation: ^4.0.1
  dio: ^4.0.0
  flutter_svg: ^0.22.0
  logger: ^1.0.0
  json_serializable: ^4.1.2
  http_mock_adapter: ^0.2.1
  connectivity: ^3.0.6
  shared_preferences: ^2.0.6
  cached_network_image: ^3.0.0
  carousel_slider: ^4.0.0-nullsafety.0
  firebase_core: ^1.2.1
  firebase_analytics: ^8.1.1
  firebase_auth: ^1.3.0
  cloud_firestore: ^2.2.1
  firebase_crashlytics: ^2.0.5
  google_sign_in: ^5.0.4
  flutter_facebook_auth: ^3.4.1
  firebase_messaging: ^10.0.1
  flutter_local_notifications: ^5.0.0+4
  google_maps_flutter: ^2.0.6
  location: ^4.2.3
  geocoder: ^0.2.1






  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter
  retrofit_generator: ^2.0.0
  build_runner: ^2.0.3



flutter: 
  uses-material-design: true
  assets:
    - assets/

